/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package admin;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.RowFilter;
import javax.swing.JTextField;
import javax.swing.JPanel;
import java.awt.GridLayout;

import java.sql.*;
import javax.swing.JOptionPane;

public class UserTable extends javax.swing.JFrame {
        DefaultTableModel model;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UserTable.class.getName());
     
    public UserTable() {
        initComponents();
    }

public UserTable(String id, String name, String email, String status) {
    initComponents();
    model = (DefaultTableModel) jTable1.getModel();
    
    // Use your config class to load data
    config.config conf = new config.config();
    conf.displayData("SELECT a_id, name, email, type, status FROM tbl_Accounts", jTable1);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton9 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 330, 210));

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 60, 30));

        jButton1.setText("Settings");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 100, -1));

        jButton2.setText("Managements");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 100, -1));

        jButton3.setText("Dashboard");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 100, -1));

        jButton5.setText("Add");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 90, 30));

        jButton6.setText("Edit");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 90, 30));

        jButton7.setText("Delete");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 90, 30));

        jButton8.setText("Log Out");
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 100, -1));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("SEARCH");
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 60, 30));

        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 270, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/board.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-290, -20, 840, 360));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void displayData() {
    try {
        // Clear existing rows
        model.setRowCount(0);
        
        // Connect to your db.db file
        Connection conn = DriverManager.getConnection("jdbc:sqlite:src/db/db.db"); 
        Statement stmt = conn.createStatement();
        
        // Query only the non-sensitive columns from tbl_Accounts
        String query = "SELECT a_id, name, email, type, status FROM tbl_Accounts";
        ResultSet rs = stmt.executeQuery(query);
        
        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("a_id"),
                rs.getString("name"),
                rs.getString("email"),
                rs.getString("type"),
                rs.getString("status")
            });
        }
        
        rs.close();
        stmt.close();
        conn.close();
    } catch (Exception e) {
        System.out.println("Error: " + e.getMessage());
    }
}
    
    private String[] showUserForm(String title, String[] data) {
    JTextField fName = new JTextField(data[0]);
    JTextField fEmail = new JTextField(data[1]);
    JTextField fStatus = new JTextField(data[2]);

    JPanel panel = new JPanel(new GridLayout(0, 1));
    panel.add(new javax.swing.JLabel("Name:"));
    panel.add(fName);
    panel.add(new javax.swing.JLabel("Email:"));
    panel.add(fEmail);
    panel.add(new javax.swing.JLabel("Status:"));
    panel.add(fStatus);

    int result = javax.swing.JOptionPane.showConfirmDialog(null, panel, title,
            javax.swing.JOptionPane.OK_CANCEL_OPTION, javax.swing.JOptionPane.PLAIN_MESSAGE);
    
    if (result == javax.swing.JOptionPane.OK_OPTION) {
        return new String[]{fName.getText(), fEmail.getText(), fStatus.getText()};
    }
    return null;
}
    
    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        jTable1.setRowSorter(sorter);
        sorter.setRowFilter(RowFilter.regexFilter("(?i)" + jTextField2.getText()));
    }//GEN-LAST:event_jTextField2KeyReleased

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String[] results = showUserForm("Add New User", new String[]{"", "", ""});
    if (results != null) {
        String sql = "INSERT INTO tbl_Accounts (name, email, status, type) VALUES (?, ?, ?, 'User')";
        try (java.sql.Connection conn = config.config.connectDB();
             java.sql.PreparedStatement pst = conn.prepareStatement(sql)) {
            pst.setString(1, results[0]);
            pst.setString(2, results[1]);
            pst.setString(3, results[2]);
            pst.executeUpdate();
            
            // Refresh table
            new config.config().displayData("SELECT a_id, name, email, type, status FROM tbl_Accounts", jTable1);
        } catch (java.sql.SQLException e) {
            System.out.println("Add Error: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
int row = jTable1.getSelectedRow();
    if (row != -1) {
        String id = jTable1.getValueAt(row, 0).toString();
        String[] currentData = {
            jTable1.getValueAt(row, 1).toString(),
            jTable1.getValueAt(row, 2).toString(),
            jTable1.getValueAt(row, 4).toString()
        };

        String[] results = showUserForm("Edit User", currentData);
        if (results != null) {
            String sql = "UPDATE tbl_Accounts SET name = ?, email = ?, status = ? WHERE a_id = ?";
            try (java.sql.Connection conn = config.config.connectDB();
                 java.sql.PreparedStatement pst = conn.prepareStatement(sql)) {
                pst.setString(1, results[0]);
                pst.setString(2, results[1]);
                pst.setString(3, results[2]);
                pst.setString(4, id);
                pst.executeUpdate();
                
                new config.config().displayData("SELECT a_id, name, email, type, status FROM tbl_Accounts", jTable1);
            } catch (java.sql.SQLException e) {
                System.out.println("Update Error: " + e.getMessage());
            }
        }
    }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        int row = jTable1.getSelectedRow();
            if (row != -1) {
                String id = jTable1.getValueAt(row, 0).toString();
                int confirm = javax.swing.JOptionPane.showConfirmDialog(null, "Delete this user?", "Warning", javax.swing.JOptionPane.YES_NO_OPTION);

                if (confirm == javax.swing.JOptionPane.YES_OPTION) {
                    try (java.sql.Connection conn = config.config.connectDB();
                         java.sql.PreparedStatement pst = conn.prepareStatement("DELETE FROM tbl_Accounts WHERE a_id = ?")) {
                        pst.setString(1, id);
                        pst.executeUpdate();

                        new config.config().displayData("SELECT a_id, name, email, type, status FROM tbl_Accounts", jTable1);
                    } catch (java.sql.SQLException e) {
                        System.out.println("Delete Error: " + e.getMessage());
                    }
                }
            }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UserTable().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
